<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net462;net472;net48;net481;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyName>System.StringVersion</AssemblyName>
    <RootNamespace>System.StringVersion</RootNamespace>
    <PackageId>StringVersion</PackageId>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0</FileVersion>
    <Version>$(VersionPrefix)1.0.0</Version>
    <Authors>ema</Authors>
    <Description>StringVersion - versatile string version comparison library</Description>
    <PackageProjectUrl>https://github.com/emako/StringVersion</PackageProjectUrl>
    <RepositoryUrl>https://github.com/emako/StringVersion</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>StringVersion Version SemVer</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\branding\logo.png" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' or '$(TargetFramework)' == 'net472' or '$(TargetFramework)' == 'net48' or '$(TargetFramework)' == 'net481' or '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
</Project>
